![](files/images/EscUpmPolit_p.gif "UPM")

## Imports

In [25]:
import pandas as pd
import csv
import numpy as np
import pickle

## Reading data

In [26]:
dtype_list=pickle.load(open('type/train.pkl','rb'))
df=pd.read_csv('../../dataset/train_data_balance_todos.csv',dtype=dtype_list)
df_original=df.copy()

In [27]:
pd.set_option('display.max_columns', None)
df

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
0,0,2148336,2853,1347,7,147,29,5,12,86,37,4,21,3,-110,4,87,117,2,2,2,38,4,3,2,28,5,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,2
1,1,1115467,5700,4569,6,118,60,3,12,67,19,2,12,5,-61,3,82,117,9,2,3,21,-1,-1,1,14,9,3,18,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,34,4
2,0,2108714,2887,2213,7,185,12,5,21,63,42,4,17,6,-87,3,65,141,9,4,2,14,9,3,2,20,10,2,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,25,5
3,1,1933373,3927,3434,6,156,56,5,18,58,37,4,21,7,-48,3,64,156,9,2,2,14,14,3,2,14,13,2,-1,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,9,17,5
4,1,1072245,3494,4779,7,193,37,5,13,50,37,4,21,5,36,4,57,193,4,2,2,46,6,3,2,14,13,2,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2890971,1,1268374,3854,3367,7,207,17,5,12,13,37,4,21,7,114,5,46,141,9,2,2,26,4,2,2,14,13,2,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,2
2890972,1,1333240,2727,1664,7,130,30,5,12,28,39,4,17,5,-63,5,20,193,4,2,2,20,6,2,2,20,15,4,20,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,12,36,2
2890973,1,1738257,4335,5710,7,150,17,5,12,11,39,4,17,6,-63,5,46,141,4,2,2,20,6,3,2,14,10,3,20,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,36,3
2890974,1,1532595,4658,3035,7,193,37,5,12,50,37,4,21,7,58,3,26,156,9,2,2,29,6,3,2,14,12,1,-1,-1,-1,2,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,12,17,7
2890975,1,2227359,3649,1622,7,207,17,5,17,13,37,4,21,4,-49,5,102,141,4,2,2,32,4,3,2,27,12,4,18,-1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,12,17,6

In [28]:
df

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
0,0,2148336,2853,1347,7,147,29,5,12,86,37,4,21,3,-110,4,87,117,2,2,2,38,4,3,2,28,5,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,2
1,1,1115467,5700,4569,6,118,60,3,12,67,19,2,12,5,-61,3,82,117,9,2,3,21,-1,-1,1,14,9,3,18,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,34,4
2,0,2108714,2887,2213,7,185,12,5,21,63,42,4,17,6,-87,3,65,141,9,4,2,14,9,3,2,20,10,2,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,25,5
3,1,1933373,3927,3434,6,156,56,5,18,58,37,4,21,7,-48,3,64,156,9,2,2,14,14,3,2,14,13,2,-1,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,9,17,5
4,1,1072245,3494,4779,7,193,37,5,13,50,37,4,21,5,36,4,57,193,4,2,2,46,6,3,2,14,13,2,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2890971,1,1268374,3854,3367,7,207,17,5,12,13,37,4,21,7,114,5,46,141,9,2,2,26,4,2,2,14,13,2,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,2
2890972,1,1333240,2727,1664,7,130,30,5,12,28,39,4,17,5,-63,5,20,193,4,2,2,20,6,2,2,20,15,4,20,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,12,36,2
2890973,1,1738257,4335,5710,7,150,17,5,12,11,39,4,17,6,-63,5,46,141,4,2,2,20,6,3,2,14,10,3,20,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,36,3
2890974,1,1532595,4658,3035,7,193,37,5,12,50,37,4,21,7,58,3,26,156,9,2,2,29,6,3,2,14,12,1,-1,-1,-1,2,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,12,17,7
2890975,1,2227359,3649,1622,7,207,17,5,17,13,37,4,21,4,-49,5,102,141,4,2,2,32,4,3,2,27,12,4,18,-1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,12,17,6

In [29]:
def filtrar(df,col):
    df1=df[df.label==1]
    a=df1[col].value_counts().cumsum()/len(df1)
    lista=a[~(a>0.9)]
    return lista.index.values

## Missing Values

In [30]:
df.shape

(2890976, 36)

In [31]:
nullvalues=(df==-1).sum(axis=0).sort_values(ascending=False)
nullvalues.head(10)

membership_life_duration       2886486
up_membership_grade            2574170
up_life_duration                893107
his_on_shelf_time               493103
his_app_size                    493103
communication_avgonline_30d      21802
age                              20389
device_price                     20389
list_time                        20389
city                              6723
dtype: int64

In [32]:
df.drop(['membership_life_duration','up_membership_grade','up_life_duration','his_on_shelf_time','his_app_size'],axis=1,inplace=True)

In [33]:
df.drop(df[df.communication_avgonline_30d==-1].index,inplace=True)
df.drop(df[df.device_price==-1].index,inplace=True)
df.drop(df[df.list_time==-1].index,inplace=True)
df.drop(df[df.age==-1].index,inplace=True)
df.drop(df[df.city==-1].index,inplace=True)

In [34]:
df.shape

(2862451, 31)

In [35]:
df.drop(['uid'],axis=1,inplace=True)

In [36]:
df.drop(['task_id'],axis=1,inplace=True)

In [37]:
df = df.drop('communication_onlinerate',axis=1)

## Dummies

In [38]:
df = pd.get_dummies(df, columns=['gender'])
df = pd.get_dummies(df, columns=['city'])
df = pd.get_dummies(df, columns=['career'])
df = pd.get_dummies(df, columns=['residence'])
df = pd.get_dummies(df, columns=['device_name'])
df = pd.get_dummies(df, columns=['dev_id'])
df = pd.get_dummies(df, columns=['spread_app_id'])
df = pd.get_dummies(df, columns=['tags'])
df = pd.get_dummies(df, columns=['indu_name'])
df = pd.get_dummies(df, columns=['adv_prim_id'])
df = pd.get_dummies(df, columns=['inter_type_cd'])
df = pd.get_dummies(df, columns=['creat_type_cd'])

In [39]:
adv_list=filtrar(df,'adv_id')
df.adv_id[~df.adv_id.isin(adv_list)] = -1
df = pd.get_dummies(df, columns=['adv_id'])
df.drop(['adv_id_-1'],axis=1,inplace=True)

C:\Users\Marta Castiella\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
df.shape

(2862451, 1394)

## Bins

In [41]:
df['device_size_binned'],bins_device_size=pd.cut(df['device_size'], 5,labels=False,retbins=True)
df['device_size_binned'].value_counts()

0    1879673
1     746956
4     144661
3      63498
2      27663
Name: device_size_binned, dtype: int64

In [42]:
df['emui_dev_binned'],bins_emui_dev=pd.cut(df['emui_dev'], 5,labels=False,retbins=True)
df['emui_dev_binned'].value_counts()

2    1525381
0     827433
4     433396
1      76235
3          6
Name: emui_dev_binned, dtype: int64

In [43]:
df['list_time_binned'],bins_list_time=pd.cut(df['list_time'], 5,labels=False,retbins=True)
df['list_time_binned'].value_counts()

2    1121143
3     678670
1     554561
4     506518
0       1559
Name: list_time_binned, dtype: int64

In [44]:
df['app_second_class_binned'],bins_app_second_class=pd.cut(df['app_second_class'], 5,labels=False,retbins=True)
df['app_second_class_binned'].value_counts()

2    1066197
3     778882
1     504236
4     461603
0      51533
Name: app_second_class_binned, dtype: int64

In [45]:
df.to_csv('../../dataset/train_data_clean_features_todos.csv',index=False)

In [46]:
import pickle

dtype_list = dict(zip(df.columns.tolist(),df.dtypes.tolist()))
pickle.dump(dtype_list,open('type/train_clean_features_todos.pkl','wb'))