![](files/images/EscUpmPolit_p.gif "UPM")

# Codigo Sergio Lopez

## Imports

In [12]:
import pandas as pd
import csv
import random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Reading data

In [13]:
#Path where the database is
path="../../dataset/train_data.csv"

#reading the database randomly
n = sum(1 for line in open(path)) - 1 #number of records in file (excludes header)
ROWS = 1000000 #desired sample size
skip = sorted(random.sample(range(1,n+1),n-ROWS)) #the 0-indexed header will not be included in the skip list
df=pd.read_csv(path, delimiter='|',nrows=ROWS,skiprows=skip)
df_original=df.copy()

pd.set_option('display.max_columns', None)
df

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
0,0,1638254,2112,6869,7,207,17,5,11,13,37,4,21,5,437,5,37,162,4,2,2,28,4,2,2,20,4,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,17,1
1,0,2057419,3357,3777,3,210,70,4,12,88,40,4,25,6,437,5,88,180,4,2,3,28,16,3,2,20,7,3,18,-1,-1,3,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,10,27,1
2,0,1612805,1575,1416,7,178,17,5,17,70,39,4,17,1,105,4,29,141,4,2,2,46,2,3,2,20,9,3,11,-1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,11,36,1
3,0,1436326,1704,2184,7,128,60,4,16,51,42,2,17,6,437,5,40,162,7,2,3,28,-1,-1,1,20,4,5,20,-1,-1,2,10^11^12^13^14^15^16^17^18^19^20^21^22^23,8,25,1
4,0,1257554,2945,5477,3,142,60,5,12,80,41,2,26,5,121,3,65,141,9,2,2,34,-1,-1,1,20,10,2,16,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1794064,2475,6282,7,168,37,5,16,44,40,4,25,7,123,3,56,141,9,2,2,29,9,3,2,20,8,4,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,7
999996,0,1955570,2203,5822,7,126,19,5,15,57,27,4,13,5,370,5,25,141,4,2,2,26,7,3,2,12,9,4,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,46,7
999997,0,2158646,5952,4158,7,207,17,5,12,13,37,4,21,5,207,5,87,117,9,2,2,32,4,3,2,28,5,4,20,1,-1,2,8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,7
999998,0,2186777,1193,3734,7,178,17,5,16,70,39,4,17,6,232,3,32,141,4,2,2,34,2,3,2,20,4,5,20,-1,-1,5,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,36,7
999999,0,1268277,1448,4758,7,144,61,5,21,41,25,4,28,5,117,4,46,141,4,4,2,20,20,3,2,14,13,2,-1,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,18,7

## Columns correction

In [14]:
df['communication_onlinerate']=df['communication_onlinerate'].apply(lambda x:x.split('^'))
dummy=pd.get_dummies(df['communication_onlinerate'].apply(pd.Series).stack()).sum(level=0)
df = pd.concat([df, dummy], axis=1)
df = df.drop('communication_onlinerate',axis=1)
df.head()

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_avgonline_30d,indu_name,pt_d,-1,0,1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,3,4,5,6,7,8,9
0,0,1638254,2112,6869,7,207,17,5,11,13,37,4,21,5,437,5,37,162,4,2,2,28,4,2,2,20,4,4,20,-1,-1,2,12,17,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
1,0,2057419,3357,3777,3,210,70,4,12,88,40,4,25,6,437,5,88,180,4,2,3,28,16,3,2,20,7,3,18,-1,-1,3,10,27,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2,0,1612805,1575,1416,7,178,17,5,17,70,39,4,17,1,105,4,29,141,4,2,2,46,2,3,2,20,9,3,11,-1,-1,2,11,36,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,0,1436326,1704,2184,7,128,60,4,16,51,42,2,17,6,437,5,40,162,7,2,3,28,-1,-1,1,20,4,5,20,-1,-1,2,8,25,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0
4,0,1257554,2945,5477,3,142,60,5,12,80,41,2,26,5,121,3,65,141,9,2,2,34,-1,-1,1,20,10,2,16,-1,-1,2,11,24,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,1,1

In [15]:
df['device_size_binned']=pd.cut(df['device_size'], 5,labels=False)
df['emui_dev_binned']=pd.cut(df['emui_dev'], 5,labels=False)
df['list_time_binned']=pd.cut(df['list_time'], 5,labels=False)

In [16]:
df

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_avgonline_30d,indu_name,pt_d,-1,0,1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,3,4,5,6,7,8,9,device_size_binned,emui_dev_binned,list_time_binned
0,0,1638254,2112,6869,7,207,17,5,11,13,37,4,21,5,437,5,37,162,4,2,2,28,4,2,2,20,4,4,20,-1,-1,2,12,17,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1
1,0,2057419,3357,3777,3,210,70,4,12,88,40,4,25,6,437,5,88,180,4,2,3,28,16,3,2,20,7,3,18,-1,-1,3,10,27,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,2,2
2,0,1612805,1575,1416,7,178,17,5,17,70,39,4,17,1,105,4,29,141,4,2,2,46,2,3,2,20,9,3,11,-1,-1,2,11,36,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,2,2
3,0,1436326,1704,2184,7,128,60,4,16,51,42,2,17,6,437,5,40,162,7,2,3,28,-1,-1,1,20,4,5,20,-1,-1,2,8,25,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,1,2,1
4,0,1257554,2945,5477,3,142,60,5,12,80,41,2,26,5,121,3,65,141,9,2,2,34,-1,-1,1,20,10,2,16,-1,-1,2,11,24,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,1,1,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1794064,2475,6282,7,168,37,5,16,44,40,4,25,7,123,3,56,141,9,2,2,29,9,3,2,20,8,4,18,-1,-1,2,13,17,7,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,2,2
999996,0,1955570,2203,5822,7,126,19,5,15,57,27,4,13,5,370,5,25,141,4,2,2,26,7,3,2,12,9,4,18,-1,-1,2,12,46,7,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,2
999997,0,2158646,5952,4158,7,207,17,5,12,13,37,4,21,5,207,5,87,117,9,2,2,32,4,3,2,28,5,4,20,1,-1,2,10,17,7,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,1,1,0,4,1
999998,0,2186777,1193,3734,7,178,17,5,16,70,39,4,17,6,232,3,32,141,4,2,2,34,2,3,2,20,4,5,20,-1,-1,5,13,36,7,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,2,1
999999,0,1268277,1448,4758,7,144,61,5,21,41,25,4,28,5,117,4,46,141,4,4,2,20,20,3,2,14,13,2,-1,-1,-1,2,13,18,7,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,3

In [17]:
df.to_csv(r'../../dataset/train_data_1.000.000_random.csv')

In [18]:
df2=df #df2 no está balanceada

In [19]:
df1=df[df.label==1]
df0=df[df.label==0]
df0=df0.iloc[0:len(df1)]
df=df1.append(df0, ignore_index=True)
df=df.sample(frac=1)
df=df.reset_index()

In [22]:
df=df.drop("index", axis=1)
df

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_avgonline_30d,indu_name,pt_d,-1,0,1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,3,4,5,6,7,8,9,device_size_binned,emui_dev_binned,list_time_binned
0,0,2170687,4155,2618,8,174,68,5,22,55,26,3,22,4,290,4,102,220,4,2,4,45,8,3,2,20,12,4,20,1,-1,10,9,22,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,1,1,2,2,3
1,1,2114846,1847,6428,7,178,17,5,12,70,39,4,17,7,154,3,65,141,9,2,2,29,2,3,2,20,10,2,16,-1,-1,2,11,36,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,0,2,3
2,0,1409831,2946,4618,7,110,38,5,14,53,28,4,27,6,221,5,32,291,4,2,2,12,14,2,2,20,4,5,20,-1,-1,3,13,30,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,2,1
3,0,1343056,5148,6476,7,184,53,5,13,49,27,4,13,5,266,4,82,117,4,4,2,34,3,2,2,20,9,3,-1,-1,-1,2,11,29,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,1,1,1,1,1,0,2,2
4,1,1639771,1847,6428,7,178,17,5,16,70,39,4,17,4,207,5,104,141,9,2,2,32,2,3,2,20,14,5,12,-1,-1,2,11,36,7,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68801,0,1365015,1704,2184,7,128,60,4,12,51,42,2,17,4,110,5,35,117,5,2,3,20,-1,-1,1,20,15,3,18,-1,-1,2,10,25,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,1,1,1,0,2,4
68802,1,1815999,2389,5768,7,177,56,5,13,31,40,4,25,4,194,3,54,141,9,2,2,42,13,3,2,12,9,3,-1,-1,-1,2,12,17,6,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,2
68803,0,1971810,1471,6236,7,156,56,5,16,58,37,4,21,4,116,3,29,141,4,2,2,38,14,3,2,14,9,3,-1,-1,-1,2,11,17,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,0,0,2
68804,0,1479577,3251,4549,7,177,56,5,17,31,40,4,25,5,120,3,91,310,4,2,2,46,13,3,2,27,14,5,20,1,-1,2,10,17,1,0,0,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0,1,1,1,4,4,4
68805,1,1917946,3104,3247,7,183,29,5,12,86,37,4,21,1,160,3,85,193,9,3,2,13,4,3,2,25,17,3,2,-1,-1,2,7,17,4,0,0,0,0,0,0,0,0,1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,1,4,4

In [24]:
df.to_csv(r'../../dataset/train_data_1.000.000_random_balanced.csv')

## Analisis

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 63 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   label                        10000 non-null  int64
 1   uid                          10000 non-null  int64
 2   task_id                      10000 non-null  int64
 3   adv_id                       10000 non-null  int64
 4   creat_type_cd                10000 non-null  int64
 5   adv_prim_id                  10000 non-null  int64
 6   dev_id                       10000 non-null  int64
 7   inter_type_cd                10000 non-null  int64
 8   slot_id                      10000 non-null  int64
 9   spread_app_id                10000 non-null  int64
 10  tags                         10000 non-null  int64
 11  app_first_class              10000 non-null  int64
 12  app_second_class             10000 non-null  int64
 13  age                          10000 non-null  int64
 14  city                         10000 non-null  int64
 15  city_rank                    10000 non-null  int64
 16  device_name                  10000 non-null  int64
 17  device_size                  10000 non-null  int64
 18  career                       10000 non-null  int64
 19  gender                       10000 non-null  int64
 20  net_type                     10000 non-null  int64
 21  residence                    10000 non-null  int64
 22  his_app_size                 10000 non-null  int64
 23  his_on_shelf_time            10000 non-null  int64
 24  app_score                    10000 non-null  int64
 25  emui_dev                     10000 non-null  int64
 26  list_time                    10000 non-null  int64
 27  device_price                 10000 non-null  int64
 28  up_life_duration             10000 non-null  int64
 29  up_membership_grade          10000 non-null  int64
 30  membership_life_duration     10000 non-null  int64
 31  consume_purchase             10000 non-null  int64
 32  communication_avgonline_30d  10000 non-null  int64
 33  indu_name                    10000 non-null  int64
 34  pt_d                         10000 non-null  int64
 35  -1                           10000 non-null  uint8
 36  0                            10000 non-null  uint8
 37  1                            10000 non-null  uint8
 38  10                           10000 non-null  uint8
 39  11                           10000 non-null  uint8
 40  12                           10000 non-null  uint8
 41  13                           10000 non-null  uint8
 42  14                           10000 non-null  uint8
 43  15                           10000 non-null  uint8
 44  16                           10000 non-null  uint8
 45  17                           10000 non-null  uint8
 46  18                           10000 non-null  uint8
 47  19                           10000 non-null  uint8
 48  2                            10000 non-null  uint8
 49  20                           10000 non-null  uint8
 50  21                           10000 non-null  uint8
 51  22                           10000 non-null  uint8
 52  23                           10000 non-null  uint8
 53  3                            10000 non-null  uint8
 54  4                            10000 non-null  uint8
 55  5                            10000 non-null  uint8
 56  6                            10000 non-null  uint8
 57  7                            10000 non-null  uint8
 58  8                            10000 non-null  uint8
 59  9                            10000 non-null  uint8
 60  device_size_binned           10000 non-null  int64
 61  emui_dev_binned              10000 non-null  int64
 62  list_time_binned             10000 non-null  int64
dtypes: int64(38), uint8(25)
memory usage: 3.1 MB

In [8]:
df.describe()

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,tags,app_first_class,app_second_class,age,city,city_rank,device_name,device_size,career,gender,net_type,residence,his_app_size,his_on_shelf_time,app_score,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_avgonline_30d,indu_name,pt_d,-1,0,1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,3,4,5,6,7,8,9,device_size_binned,emui_dev_binned,list_time_binned
count,10000.000000,1.000000e+04,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,0.032000,1.618894e+06,3436.101800,3969.46150,6.505900,159.001900,41.286800,4.657100,15.244800,51.593400,34.341100,3.573600,22.116400,5.076500,264.968500,3.871300,62.44500,157.897100,6.205200,2.44470,2.211000,28.299900,6.520600,2.050500,1.788300,19.291600,9.224900,3.476800,12.58860,-0.755400,-0.966400,2.551500,11.141000,26.4709,3.998800,0.008800,0.260000,0.349000,0.971600,0.975900,0.979800,0.982000,0.98380,0.985400,0.986800,0.987400,0.988700,0.989600,0.426400,0.990500,0.990700,0.990600,0.989300,0.472400,0.519200,0.612200,0.806000,0.909200,0.951000,0.965200,0.524400,1.760100,2.34010
std,0.176009,3.588762e+05,1430.546208,1723.45949,1.219637,31.053565,17.370311,0.706661,3.180485,25.034255,8.186639,0.816241,3.615461,1.398229,101.361651,0.908966,24.96178,45.007278,2.482037,0.82487,0.427899,10.584213,5.847118,1.605555,0.408534,4.522435,3.654046,1.161808,9.08589,0.659405,0.792423,1.707993,1.651361,11.0305,2.015144,0.093399,0.438656,0.476678,0.166121,0.153367,0.140691,0.132958,0.12625,0.119951,0.114136,0.111546,0.105704,0.101454,0.494578,0.097009,0.095992,0.096502,0.102891,0.499263,0.499656,0.487273,0.395449,0.287339,0.215879,0.183282,0.993229,1.304576,1.01397
min,0.000000,1.000045e+06,1002.000000,1016.00000,2.000000,102.000000,11.000000,2.000000,11.000000,11.000000,11.000000,2.000000,11.000000,-1.000000,101.000000,2.000000,12.00000,103.000000,2.000000,2.00000,2.000000,11.000000,-1.000000,-1.000000,1.000000,11.000000,-2.000000,-1.000000,-1.00000,-1.000000,-1.000000,2.000000,-1.000000,11.0000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,0.000000,1.309686e+06,2229.000000,2504.00000,6.000000,134.000000,29.000000,5.000000,12.000000,31.000000,36.000000,4.000000,21.000000,4.000000,193.000000,3.000000,41.00000,141.000000,4.000000,2.00000,2.000000,20.000000,4.000000,2.000000,2.000000,14.000000,7.000000,3.000000,-1.00000,-1.000000,-1.000000,2.000000,10.000000,17.0000,2.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.00000
50%,0.000000,1.617709e+06,3370.000000,4056.00000,7.000000,156.000000,37.000000,5.000000,16.000000,50.000000,37.000000,4.000000,21.000000,5.000000,257.000000,4.000000,57.00000,141.000000,5.000000,2.00000,2.000000,29.000000,5.000000,3.000000,2.000000,20.000000,9.000000,4.000000,18.00000,-1.000000,-1.000000,2.000000,11.000000,24.0000,4.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,2.000000,2.00000
75%,0.000000,1.928666e+06,4625.000000,5472.00000,7.000000,180.000000,60.000000,5.000000,17.000000,78.000000,40.000000,4.000000,25.000000,6.000000,357.000000,5.000000,87.00000,162.000000,9.000000,2.00000,2.000000,37.000000,11.000000,3.000000,2.000000,20.000000,12.000000,4.000000,20.00000,-1.000000,-1.000000,2.000000,12.000000,36.0000,6.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,3.00000
max,1.000000,2.237485e+06,5990.000000,7018.00000,9.000000,214.000000,72.000000,5.000000,22.000000,89.000000,42.000000,4.000000,29.000000,7.000000,444.000000,5.000000,104.00000,349.000000,10.000000,4.00000,6.000000,46.000000,21.000000,3.000000,2.000000,28.000000,17.000000,7.000000,20.00000,3.000000,18.000000,10.000000,13.000000,52.0000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000,4.00000

In [9]:
print("Labels con valor 1: "+str(sum(df.label ==1)))

Labels con valor 1: 320

In [44]:
df_sort.iloc[0:50]

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,...,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
766210,0,1658856,2233,1003,8,142,60,5,12,80,...,12,2,20,-1,-1,2,9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,8,42,1
309752,0,1901996,2233,1003,8,142,60,5,12,80,...,17,2,-1,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,42,1
57917,0,1809663,2233,1003,8,142,60,5,12,80,...,13,2,18,-1,-1,2,4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^2...,11,42,1
661826,0,1028309,2233,1003,8,142,60,5,12,80,...,10,2,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,42,1
683602,0,1255287,3537,1004,8,142,60,5,12,80,...,8,2,-1,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,12,42,1
27955,0,2053896,3537,1004,8,142,60,5,12,80,...,12,2,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16,4,42,1
263991,0,1281057,5732,1005,7,108,26,5,17,27,...,4,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,12,1
644236,0,1679010,5732,1005,7,108,26,5,17,27,...,8,5,20,-1,-1,2,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,12,12,1
65498,0,1306058,5732,1005,7,108,26,5,14,27,...,4,5,20,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,12,1
551099,0,1660938,5732,1005,7,108,26,5,12,27,...,5,4,20,-1,-1,5,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,12,1
387402,0,1227412,5732,1005,7,108,26,5,11,27,...,4,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,12,1
830465,0,1262157,5732,1005,7,108,26,5,14,27,...,4,4,20,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,12,1
583518,0,1584803,5732,1005,7,108,26,5,17,27,...,12,4,18,-1,-1,7,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,12,1
825260,0,1365345,5732,1005,7,108,26,5,12,27,...,15,4,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,12,1
982566,0,1384806,5732,1005,7,108,26,5,19,27,...,9,4,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,12,1
879741,0,2095822,2107,1009,3,142,60,5,16,80,...,4,4,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,42,1
23033,0,1608463,2107,1009,3,142,60,5,12,80,...,9,3,20,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,42,1
392154,0,1127341,2107,1009,3,142,60,5,12,80,...,9,3,-1,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,42,1
918425,0,2012465,2107,1009,3,142,60,5,17,80,...,17,5,20,-1,-1,5,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,42,1
750144,0,2134742,2107,1009,3,142,60,5,17,80,...,4,5,20,-1,-1,9,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,11,42,1
351739,0,1852747,2107,1009,3,142,60,5,17,80,...,10,2,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,42,1
201099,0,2072959,2107,1009,3,142,60,5,12,80,...,9,3,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,42,1
919082,0,1630115,2107,1009,3,142,60,5,13,80,...,16,1,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,42,1
975931,0,2186562,2107,1009,3,142,60,5,17,80,...,8,5,16,-1,-1,2,4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^2...,11,42,1
770468,0,1549079,2107,1009,3,142,60,5,12,80,...,13,2,20,1,-1,2,8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,42,1
346947,0,1158839,2107,1009,3,142,60,5,12,80,...,10,3,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,42,1
595663,0,1041109,1358,1011,7,142,36,4,12,80,...,5,4,20,1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,12,42,1
424625,0,1302288,1358,1011,7,142,36,4,12,80,...,9,3,18,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,12,42,1
773170,0,1956717,1358,1011,7,142,36,4,17,80,...,10,3,-1,-1,-1,2,4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^2...,11,42,1
777893,0,1250632,1358,1011,7,142,36,4,12,80,...,5,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,42,1
384588,0,1330414,5740,1014,7,108,26,5,17,27,...,15,4,-1,-1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,12,12,1
739890,0,1674932,5740,1014,7,108,26,5,12,27,...,5,4,20,1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,13,12,1
6271,0,1839977,5740,1014,6,108,26,5,18,27,...,5,4,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,12,1
284228,1,2172573,5740,1014,7,108,26,5,17,27,...,8,5,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,12,1
624270,0,1674932,5740,1014,7,108,26,5,13,27,...,5,4,20,1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,13,12,1
18854,0,1479617,4944,1015,6,133,37,5,18,34,...,12,2,16,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,17,1
335980,0,1405534,4944,1015,7,133,37,5,11,34,...,17,4,-1,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,17,1
848960,0,1124447,4944,1015,7,133,37,5,11,34,...,14,5,20,-1,-1,2,1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^1...,10,17,1
115803,0,1275854,4944,1015,6,133,37,5,18,34,...,10,2,20,-1,-1,2,9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,9,17,1
683422,0,1580399,4944,1015,6,133,37,5,18,34,...,15,4,-1,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,17,1
472955,0,1115804,4944,1015,7,133,37,5,12,34,...,7,1,-1,-1,-1,2,9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,9,17,1
206552,0,2088910,4944,1015,7,133,37,5,11,34,...,17,5,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,17,1
716302,0,1389292,4944,1015,6,133,37,5,18,34,...,17,2,20,-1,-1,10,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,1
447741,0,2158909,4944,1015,6,133,37,5,18,34,...,10,2,20,1,-1,2,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,12,17,1
561703,0,1579627,4944,1015,7,133,37,5,11,34,...,8,4,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,17,1
435107,0,1619769,4944,1015,7,133,37,5,11,34,...,12,4,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,17,1
769771,0,1459981,4944,1015,6,133,37,5,18,34,...,10,1,12,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,17,1
936853,0,2137404,4944,1015,7,133,37,5,16,34,...,4,4,20,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,17,1
625638,0,1788750,4944,1015,7,133,37,5,11,34,...,4,4,18,-1,-1,2,0^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,10,17,1
540515,0,1478704,4944,1015,7,133,37,5,16,34,...,14,5,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,1

In [45]:
df_sort.to_csv("dfsgbfediu.csv")

In [46]:
#Path where the database is
path="../dataset/train_data.csv"

#reading the database
d2f=pd.read_csv(path, delimiter='|',nrows=1000)
d2f

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,...,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
0,0,1638254,2112,6869,7,207,17,5,11,13,...,4,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,12,17,1
1,0,1161786,3104,3247,7,183,29,5,17,86,...,4,4,18,-1,-1,2,3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20...,12,17,1
2,0,1814783,5890,4183,7,178,17,5,11,70,...,4,5,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,11,36,1
3,0,1468996,1993,5405,7,207,17,5,21,13,...,7,3,-1,-1,-1,2,5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^...,11,17,1
4,0,2164010,5439,4677,2,138,24,5,12,33,...,7,3,-1,-1,-1,2,2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18^19^...,11,20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,2094931,4155,2618,8,174,68,5,17,55,...,12,2,18,-1,-1,8,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,22,1
996,0,1647308,3854,3367,7,207,17,5,11,13,...,8,5,20,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,17,1
997,0,1654443,2946,6698,7,110,38,5,21,53,...,9,3,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,30,1
998,0,1719276,4263,4691,7,137,37,5,12,34,...,15,3,16,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,1
999,0,1220598,3747,4461,7,207,17,5,12,13,...,7,3,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,17,1

In [50]:
len(d2f["adv_id"].unique())

405

In [49]:
len(d2f["task_id"].unique())

399

In [52]:
d2f.sort_values('adv_id')

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,...,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_onlinerate,communication_avgonline_30d,indu_name,pt_d
200,0,1929699,3348,1021,2,160,58,5,21,79,...,8,2,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,42,1
675,0,1546258,2306,1022,6,132,60,3,11,78,...,8,4,-1,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,11,47,1
873,0,1483880,3942,1026,7,133,37,5,11,34,...,14,5,18,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,17,1
745,0,1202467,1665,1037,7,178,60,5,17,70,...,7,3,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,24,1
158,0,1719743,5770,1044,7,203,69,5,11,62,...,4,4,20,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,16,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,0,1718124,5270,6908,7,147,29,5,12,86,...,5,4,8,-1,-1,2,13^14^15^16^17^18^19^20^21^22^23,7,17,1
543,0,2058411,5270,6908,7,147,29,5,12,86,...,5,4,18,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,1
227,0,1423210,5270,6908,7,147,29,5,12,86,...,14,4,12,-1,-1,2,6^7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,1
945,0,1840887,4208,6941,7,115,54,5,12,72,...,5,4,-1,-1,-1,2,0^1^2^3^4^5^6^7^8^9^10^11^12^13^14^15^16^17^18...,13,26,1
621,0,1535369,1677,7016,6,167,37,5,18,44,...,6,1,-1,-1,-1,2,7^8^9^10^11^12^13^14^15^16^17^18^19^20^21^22^23,10,17,1

In [54]:
len(d2f["dev_id"].unique())

36

In [81]:
for column in d2f:
    print(column )
    print(len(d2f[column].unique()))

label
2
uid
993
task_id
399
adv_id
405
creat_type_cd
8
adv_prim_id
65
dev_id
36
inter_type_cd
3
slot_id
11
spread_app_id
47
tags
23
app_first_class
3
app_second_class
16
age
8
city
236
city_rank
4
device_name
65
device_size
23
career
9
gender
3
net_type
3
residence
33
his_app_size
18
his_on_shelf_time
4
app_score
2
emui_dev
13
list_time
15
device_price
6
up_life_duration
16
up_membership_grade
4
membership_life_duration
3
consume_purchase
8
communication_onlinerate
30
communication_avgonline_30d
12
indu_name
29
pt_d
1

In [7]:
df.corr()

,label,uid,task_id,adv_id,creat_type_cd,adv_prim_id,dev_id,inter_type_cd,slot_id,spread_app_id,...,emui_dev,list_time,device_price,up_life_duration,up_membership_grade,membership_life_duration,consume_purchase,communication_avgonline_30d,indu_name,pt_d
label,1.000000,0.015335,0.018545,0.016121,0.022799,0.073800,-0.048258,0.027151,-0.058878,-0.025406,...,-0.032033,0.024998,-0.069136,-0.045464,-0.019194,0.008866,0.000554,-0.010893,-0.042012,NaN
uid,0.015335,1.000000,-0.000618,-0.004067,0.005870,0.003663,-0.009396,0.009849,0.021992,0.011160,...,-0.005071,-0.008643,0.004416,-0.034524,-0.024278,-0.000487,0.001466,-0.008826,0.004861,NaN
task_id,0.018545,-0.000618,1.000000,0.022692,0.067418,0.027388,-0.023516,0.030885,-0.029394,-0.139542,...,-0.031438,-0.005457,-0.023419,0.018948,-0.003127,-0.006910,0.024934,0.001611,-0.010267,NaN
adv_id,0.016121,-0.004067,0.022692,1.000000,0.031206,0.051723,-0.086181,0.014748,-0.017044,-0.030287,...,-0.002305,0.030268,-0.019313,-0.003933,-0.002847,0.013556,-0.010761,-0.002038,-0.039236,NaN
creat_type_cd,0.022799,0.005870,0.067418,0.031206,1.000000,0.089735,-0.277838,0.319469,-0.008751,-0.343446,...,-0.002300,0.027827,-0.048869,-0.025832,-0.017883,-0.012774,0.020604,-0.005623,-0.246808,NaN
adv_prim_id,0.073800,0.003663,0.027388,0.051723,0.089735,1.000000,-0.096820,0.211429,-0.017605,-0.349315,...,-0.032955,0.035159,-0.056736,-0.014425,-0.028522,0.006948,-0.026622,-0.023077,-0.250994,NaN
dev_id,-0.048258,-0.009396,-0.023516,-0.086181,-0.277838,-0.096820,1.000000,-0.450042,0.027874,0.372198,...,0.075396,-0.044477,0.138418,0.086439,0.054632,0.013253,0.059032,0.015537,0.124624,NaN
inter_type_cd,0.027151,0.009849,0.030885,0.014748,0.319469,0.211429,-0.450042,1.000000,0.038663,-0.313539,...,-0.075356,0.048444,-0.203926,-0.092382,-0.050005,-0.010709,-0.018451,-0.017019,-0.273163,NaN
slot_id,-0.058878,0.021992,-0.029394,-0.017044,-0.008751,-0.017605,0.027874,0.038663,1.000000,-0.061245,...,-0.001338,-0.016129,0.016643,0.011591,0.001224,-0.026031,-0.001333,0.000087,-0.029543,NaN
spread_app_id,-0.025406,0.011160,-0.139542,-0.030287,-0.343446,-0.349315,0.372198,-0.313539,-0.061245,1.000000,...,0.050128,-0.038841,0.097655,0.036520,0.024855,0.007222,0.018075,-0.001207,0.267412,NaN
tags,0.025556,0.005792,-0.106073,-0.060851,0.038989,0.274477,-0.270267,0.565196,0.004786,-0.044650,...,-0.056084,-0.003283,-0.091920,-0.071079,-0.026206,0.019193,-0.049796,-0.003679,-0.016111,NaN
app_first_class,0.054177,0.020822,-0.036921,0.046824,0.230478,0.319308,-0.532402,0.598570,0.026719,-0.313823,...,-0.060121,0.032380,-0.142505,-0.089792,-0.027287,0.009461,-0.059117,-0.013264,-0.255814,NaN
app_second_class,-0.028380,0.012441,-0.136746,0.039515,-0.281778,-0.125131,0.290807,-0.160853,0.025980,0.329242,...,0.050883,0.011031,0.058730,-0.007543,0.016126,-0.000955,0.021632,-0.021618,-0.076908,NaN
age,-0.031381,-0.018453,-0.003340,-0.006883,-0.065553,-0.038179,0.016434,-0.024983,-0.018609,-0.011196,...,0.023046,-0.263107,0.086432,0.068529,0.052863,0.003201,-0.025347,0.133129,0.011365,NaN
city,0.002928,0.016450,-0.018240,0.001599,-0.000390,-0.004098,-0.005499,-0.016843,-0.002119,-0.003780,...,-0.004817,-0.007247,0.000734,-0.028346,0.003778,0.033797,-0.032360,0.018698,-0.007267,NaN
city_rank,-0.029285,0.006914,-0.039868,-0.011774,-0.043473,-0.075059,0.053491,-0.104953,-0.018145,0.045102,...,0.076637,-0.024731,0.132344,0.072324,0.062808,0.000692,0.003711,0.013847,0.029966,NaN
device_name,0.000016,0.009163,-0.005477,0.018836,0.001074,0.003131,0.016782,-0.003039,0.004938,-0.006517,...,0.382122,0.290766,0.056035,-0.001252,0.005377,0.006071,-0.004514,-0.022558,0.010652,NaN
device_size,-0.010576,-0.006079,-0.004667,0.010200,0.010093,-0.015102,0.022215,-0.041157,0.086417,0.018190,...,0.103616,0.305381,0.170174,0.009073,0.021287,-0.002025,0.014880,-0.063287,-0.017959,NaN
career,0.021417,0.029550,-0.015634,0.007121,0.034132,0.010714,-0.070809,0.097003,-0.005148,-0.028320,...,-0.094787,0.117122,-0.206158,-0.224239,-0.078915,0.012536,-0.086106,-0.086806,-0.037607,NaN
gender,-0.000446,0.005739,0.017508,0.018468,0.053223,0.034192,-0.089799,0.047228,-0.008612,-0.050858,...,-0.034983,0.011631,-0.070396,0.018690,-0.061286,-0.019101,-0.025249,-0.028062,-0.018920,NaN
net_type,-0.022175,-0.001656,-0.081766,-0.037638,-0.267265,-0.220275,0.324351,-0.510965,-0.010313,0.346589,...,0.049350,-0.061341,0.139925,0.063438,0.054067,0.009279,0.078784,0.004059,0.333727,NaN
residence,0.007842,0.020419,-0.017820,-0.000634,0.019134,0.001627,-0.011966,-0.007968,0.002819,-0.001519,...,-0.024094,0.003907,0.016962,-0.011701,-0.013255,-0.027689,-0.010822,-0.013730,-0.022939,NaN
his_app_size,0.022626,0.021324,-0.013004,0.128313,0.065333,0.114210,0.035611,0.290909,0.058634,-0.147862,...,-0.011524,0.024289,-0.051479,-0.026652,0.017426,0.019352,0.010587,0.002340,-0.293933,NaN
his_on_shelf_time,0.046429,0.022856,-0.047304,0.018106,0.224083,0.262425,-0.407472,0.583354,0.022452,-0.196404,...,-0.056825,0.024659,-0.136408,-0.071977,-0.007254,0.011248,-0.020789,-0.015019,-0.199284,NaN
app_score,0.053770,0.021917,-0.016551,0.048247,0.245804,0.305727,-0.512855,0.609612,0.022411,-0.311752,...,-0.056188,0.025981,-0.136702,-0.075029,-0.015643,0.008358,-0.022049,-0.008530,-0.237411,NaN
emui_dev,-0.032033,-0.005071,-0.031438,-0.002305,-0.002300,-0.032955,0.075396,-0.075356,-0.001338,0.050128,...,1.000000,-0.057764,0.460070,0.123269,0.094494,0.028088,0.051653,0.033023,0.026820,NaN
list_time,0.024998,-0.008643,-0.005457,0.030268,0.027827,0.035159,-0.044477,0.048444,-0.016129,-0.038841,...,-0.057764,1.000000,-0.158265,-0.110859,-0.058425,0.003177,-0.031502,-0.059046,-0.047064,NaN
device_price,-0.069136,0.004416,-0.023419,-0.019313,-0.048869,-0.056736,0.138418,-0.203926,0.016643,0.097655,...,0.460070,-0.158265,1.000000,0.232928,0.146168,0.022663,0.112352,0.110189,0.096912,NaN
up_life_duration,-0.045464,-0.034524,0.018948,-0.003933,-0.025832,-0.014425,0.086439,-0.092382,0.011591,0.036520,...,0.123269,-0.110859,0.232928,1.000000,0.303546,0.038344,0.242937,0.137008,0.041866,NaN
up_membership_grade,-0.019194,-0.024278,-0.003127,-0.002847,-0.017883,-0.028522,0.054632,-0.050005,0.001224,0.024855,...,0.094494,-0.058425,0.146168,0.303546,1.000000,0.204404,0.144827,0.045482,0.025783,NaN
membership_life_duration,0.008866,-0.000487,-0.006910,0.013556,-0.012774,0.006948,0.013253,-0.010709,-0.026031,0.007222,...,0.028088,0.003177,0.022663,0.038344,0.204404,1.000000,-0.003661,0.018637,0.000346,NaN
consume_purchase,0.000554,0.001466,0.024934,-0.010761,0.020604,-0.026622,0.059032,-0.018451,-0.001333,0.018075,...,0.051653,-0.031502,0.112352,0.242937,0.144827,-0.003661,1.000000,0.053859,0.004550,NaN
communication_avgonline_30d,-0.010893,-0.008826,0.001611,-0.002038,-0.005623,-0.023077,0.015537,-0.017019,0.000087,-0.001207,...,0.033023,-0.059046,0.110189,0.137008,0.045482,0.018637,0.053859,1.000000,-0.003533,NaN
indu_name,-0.042012,0.004861,-0.010267,-0.039236,-0.246808,-0.250994,0.124624,-0.273163,-0.029543,0.267412,...,0.026820,-0.047064,0.096912,0.041866,0.025783,0.000346,0.004550,-0.003533,1.000000,NaN
pt_d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN